PROGS = turbostat

installdir = /usr/sbin

include $(top_rulesdir)/Makefile.inc

CPPFLAGS += -DMSRHEADER='"../../../../arch/x86/include/asm/msr-index.h"'
CPPFLAGS += -DINTEL_FAMILY_HEADER='"../../../../arch/x86/include/asm/intel-family.h"'
